# Generated by Django 4.0 on 2022-08-22 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_burndownchart_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burndownchart',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chart', to='tickets.project'),
        ),
    ]
