# Generated by Django 4.0 on 2022-08-23 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_burndownchart_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burndownchart',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.project'),
        ),
    ]
